<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PekerjaansTableSeeder extends Seeder
{
    public function run(): void
    {
        $pekerjaans = [
            ['kode' => 1, 'nama_pekerjaan' => 'Belum/Tidak Bekerja'],
            ['kode' => 2, 'nama_pekerjaan' => 'Mengurus Rumah Tangga'],
            ['kode' => 3, 'nama_pekerjaan' => 'Pelajar/Mahasiswa'],
            ['kode' => 4, 'nama_pekerjaan' => 'Pensiunan'],
            ['kode' => 5, 'nama_pekerjaan' => 'Pegawai Negeri Sipil (PNS)'],
            ['kode' => 6, 'nama_pekerjaan' => 'Tentara Nasional Indonesia (TNI)'],
            ['kode' => 7, 'nama_pekerjaan' => 'Kepolisian RI (POLRI)'],
            ['kode' => 8, 'nama_pekerjaan' => 'Perdagangan'],
            ['kode' => 9, 'nama_pekerjaan' => 'Petani/Pekebun'],
            ['kode' => 10, 'nama_pekerjaan' => 'Peternak'],
            ['kode' => 11, 'nama_pekerjaan' => 'Nelayan/Perikanan'],
            ['kode' => 12, 'nama_pekerjaan' => 'Industri'],
            ['kode' => 13, 'nama_pekerjaan' => 'Konstruksi'],
            ['kode' => 14, 'nama_pekerjaan' => 'Transportasi'],
            ['kode' => 15, 'nama_pekerjaan' => 'Karyawan Swasta'],
            ['kode' => 16, 'nama_pekerjaan' => 'Karyawan BUMN'],
            ['kode' => 17, 'nama_pekerjaan' => 'Karyawan BUMD'],
            ['kode' => 18, 'nama_pekerjaan' => 'Karyawan Honorer'],
            ['kode' => 19, 'nama_pekerjaan' => 'Buruh Harian Lepas'],
            ['kode' => 20, 'nama_pekerjaan' => 'Buruh Tani/Perkebunan'],
            ['kode' => 21, 'nama_pekerjaan' => 'Buruh Nelayan/Perikanan'],
            ['kode' => 22, 'nama_pekerjaan' => 'Buruh Peternakan'],
            ['kode' => 23, 'nama_pekerjaan' => 'Pembantu Rumah Tangga'],
            ['kode' => 24, 'nama_pekerjaan' => 'Tukang Cukur'],
            ['kode' => 25, 'nama_pekerjaan' => 'Tukang Listrik'],
            ['kode' => 26, 'nama_pekerjaan' => 'Tukang Batu'],
            ['kode' => 27, 'nama_pekerjaan' => 'Tukang Kayu'],
            ['kode' => 28, 'nama_pekerjaan' => 'Tukang Sol Sepatu'],
            ['kode' => 29, 'nama_pekerjaan' => 'Tukang Las/Pandai Besi'],
            ['kode' => 30, 'nama_pekerjaan' => 'Tukang Jahit'],
            ['kode' => 31, 'nama_pekerjaan' => 'Tukang Gigi'],
            ['kode' => 32, 'nama_pekerjaan' => 'Penata Rias'],
            ['kode' => 33, 'nama_pekerjaan' => 'Penata Busana'],
            ['kode' => 34, 'nama_pekerjaan' => 'Penata Rambut'],
            ['kode' => 35, 'nama_pekerjaan' => 'Mekanik'],
            ['kode' => 36, 'nama_pekerjaan' => 'Seniman'],
            ['kode' => 37, 'nama_pekerjaan' => 'Tabib'],
            ['kode' => 38, 'nama_pekerjaan' => 'Paraji'],
            ['kode' => 39, 'nama_pekerjaan' => 'Perancang Busana'],
            ['kode' => 40, 'nama_pekerjaan' => 'Penterjemah'],
            ['kode' => 41, 'nama_pekerjaan' => 'Imam Masjid'],
            ['kode' => 42, 'nama_pekerjaan' => 'Pendeta'],
            ['kode' => 43, 'nama_pekerjaan' => 'Pastor'],
            ['kode' => 44, 'nama_pekerjaan' => 'Wartawan'],
            ['kode' => 45, 'nama_pekerjaan' => 'Ustadz/Mubaligh'],
            ['kode' => 46, 'nama_pekerjaan' => 'Juru Masak'],
            ['kode' => 47, 'nama_pekerjaan' => 'Promotor Acara'],
            ['kode' => 48, 'nama_pekerjaan' => 'Anggota DPR-RI'],
            ['kode' => 49, 'nama_pekerjaan' => 'Anggota DPD'],
            ['kode' => 50, 'nama_pekerjaan' => 'Anggota BPK'],
            ['kode' => 51, 'nama_pekerjaan' => 'Presiden'],
            ['kode' => 52, 'nama_pekerjaan' => 'Wakil Presiden'],
            ['kode' => 53, 'nama_pekerjaan' => 'Anggota Mahkamah'],
            ['kode' => 54, 'nama_pekerjaan' => 'Konstitusi'],
            ['kode' => 55, 'nama_pekerjaan' => 'Anggota Kabinet/ Kementrian'],
            ['kode' => 56, 'nama_pekerjaan' => 'Duta Besar'],
            ['kode' => 57, 'nama_pekerjaan' => 'Gubernur'],
            ['kode' => 58, 'nama_pekerjaan' => 'Wakil Gubernur'],
            ['kode' => 59, 'nama_pekerjaan' => 'Bupati'],
            ['kode' => 60, 'nama_pekerjaan' => 'Wakil Bupati'],
            ['kode' => 61, 'nama_pekerjaan' => 'Walikota'],
            ['kode' => 62, 'nama_pekerjaan' => 'Wakil Walikota'],
            ['kode' => 63, 'nama_pekerjaan' => 'Anggota DPRD Provinsi/ Anggota DPRD Kabupaten/Kota'],
            ['kode' => 64, 'nama_pekerjaan' => 'Dosen'],
            ['kode' => 65, 'nama_pekerjaan' => 'Guru'],
            ['kode' => 66, 'nama_pekerjaan' => 'Pilot'],
            ['kode' => 67, 'nama_pekerjaan' => 'Pengacara'],
            ['kode' => 68, 'nama_pekerjaan' => 'Notaris'],
            ['kode' => 69, 'nama_pekerjaan' => 'Arsitek'],
            ['kode' => 70, 'nama_pekerjaan' => 'Akuntan'],
            ['kode' => 71, 'nama_pekerjaan' => 'Konsultan'],
            ['kode' => 72, 'nama_pekerjaan' => 'Dokter'],
            ['kode' => 73, 'nama_pekerjaan' => 'Bidan'],
            ['kode' => 74, 'nama_pekerjaan' => 'Perawat'],
            ['kode' => 75, 'nama_pekerjaan' => 'Apoteker'],
            ['kode' => 76, 'nama_pekerjaan' => 'Psikiater/Psikolog'],
            ['kode' => 77, 'nama_pekerjaan' => 'Penyiar Televisi'],
            ['kode' => 78, 'nama_pekerjaan' => 'Penyiar Radio'],
            ['kode' => 79, 'nama_pekerjaan' => 'Pelaut'],
            ['kode' => 80, 'nama_pekerjaan' => 'Peneliti'],
            ['kode' => 81, 'nama_pekerjaan' => 'Sopir'],
            ['kode' => 82, 'nama_pekerjaan' => 'Pialang'],
            ['kode' => 83, 'nama_pekerjaan' => 'Paranormal'],
            ['kode' => 84, 'nama_pekerjaan' => 'Pedagang'],
            ['kode' => 85, 'nama_pekerjaan' => 'Perangkat Desa'],
            ['kode' => 86, 'nama_pekerjaan' => 'Kepala Desa'],
            ['kode' => 87, 'nama_pekerjaan' => 'Biarawati'],
            ['kode' => 88, 'nama_pekerjaan' => 'Wiraswasta'],
            ['kode' => 89, 'nama_pekerjaan' => 'Lainnya'],
        ];

        DB::table('pekerjaans')->insert($pekerjaans);
    }
}
